ORG 0000H
	JMP INICIO
ORG 0100H


INICIO:
	MOV A, PRIMEIRA_VEZ
	JNZ JA_INICIOU
	;CALL INICIALIZA_INIMIGOS
JA_INICIOU: 
	CALL MOVE_INIMIGOS

MOVE_INIMIGOS:	
	CALL ATUALIZA_DIRECAO
	RET


ATUALIZA_DIRECAO:
	CALL VIVOS
	MOV A,INIMIGOS_DIRECAO ; 0 SE DIREITA 1 E ESQUERDA
	JZ ATUALMENTE_DIREITA
	JMP	ATUALMENTE_ESQUERDA
	
	ATUALMENTE_DIREITA:
		; PROCURA O MAIOR X
			MOV A, MAIOR_X
			ADD A, #0BH ;TENHO QUE COLOCAR NO EQU O TAMANHO DA COISA
			ADD A, #0FH ; TENHO QUE COLOCAR NO EQU O DESLOCAMENTO
			SUBB A, #7FH ; TENHO QUE COLOCAR NO EQU TAMANHO MAXIMO NO X
			JC CONTINUA_DESLOCAMENTO
			MOV INIMIGOS_DIRECAO, #01H
			MOV FLAG_TROCOU_DIRECAO, #01H
			JMP	CONTINUA_DESLOCAMENTO
	
	ATUALMENTE_ESQUERDA:
		; PROCURA O MENOR X
			MOV A, MENOR_Y
			SUBB A, #0FH ; TENHO QUE COLOCAR NO EQU O DESLOCAMENTO
			JNC CONTINUA_DESLOCAMENTO            	 ; SE BAIXOU DE ZERO ENTÃO PASSOU
			MOV INIMIGOS_DIRECAO, #00H
			MOV FLAG_TROCOU_DIRECAO, #01H
			JMP	CONTINUA_DESLOCAMENTO
	CONTINUA_DESLOCAMENTO:
			MOV A, FLAG_TROCOU_DIRECAO
			JZ MOVER_EFETIVAMENTE

			 MOV A, MENOR_Y
			 ADD A, #01H ;DESLOCAMENTO DO Y          ; TESTO SE OS MOSTROS CHEGARAM NA TERRA OU SEI LA
			 CJNE A, #07H, MOVER_EFETIVAMENTE
			 MOV FLAG_GAME_OVER, #01H
			JMP FIM_MOVIMENTACAO

	  MOVER_EFETIVAMENTE:		
			 MOV A, #ENEMIES
			 MOV R0, A
			 MOV A, @R0
			 MOV R1, #00H

			 PROXIMO_INIMIGO:
		     
			 JZ MOVER_EFETIVAMENTE_DIREITA
			 JMP MOVER_EFETIVAMENTE_ESQUERDA
			 MOVER_EFETIVAMENTE_DIREITA:
			 ADD A, #0FH
			 MOV @R0, A
			 JMP CONTINUA_DESLOCAMENTO_2
			 MOVER_EFETIVAMENTE_ESQUERDA:
			 SUBB A, #0FH
			 MOV @R0, A
			  
			 JMP CONTINUA_DESLOCAMENTO_2

			 CONTINUA_DESLOCAMENTO_2:

			INC R0
			MOV A, FLAG_TROCOU_DIRECAO
			JZ NAO_MEXE_Y

			MOV A, @R0 
			ADD A,  #01H 
			MOV @R0, A

			NAO_MEXE_Y:
			MOV A, NUMERO_DE_VIVOS
			INC R1
			SUBB A, R1
			JZ FIM_MOVIMENTACAO

			INC R0
			JMP PROXIMO_INIMIGO

	 		MOV FLAG_TROCOU_DIRECAO, #00H
	FIM_MOVIMENTACAO:
RET

 VIVOS:
 	MOV A, #ENEMIES
	MOV R0, A	                   ;PONTEIROS PARA ENIMIES
	MOV R1, A
	MOV R2, #00H 			  ; R2 CONTA QUANTAS VEZES PASSOU (8 VEZES POIS 8 INIMIGOS)
	MOV NUMERO_DE_VIVOS, #00H	
    BUSCA_VIVOS:
		MOV A, @R0
		CJNE A, #0FFH, NAO_MORREU
		INC R0
		INC R0
		INC R2
		CJNE R2 , #08H, BUSCA_VIVOS 
		JMP FIM_DE_VIVOS
	 NAO_MORREU:

		 MOV A, NUMERO_DE_VIVOS
		 INC A
		 MOV NUMERO_DE_VIVOS, A


	 	MOV A,@R0	;PASSO X
		MOV @R1, A
		MOV MEU_AUX, A 
		CALL F_MAIOR_X
		CALL F_MENOR_X


	 	INC R0 ; INCREMENTO R0 E R1
		INC R1

		MOV A,@R0 ;PASSO Y
		MOV @R1, A
		MOV MEU_AUX, A
		CALL F_MENOR_Y

		INC R2
		CJNE R2 , #08H,  BUSCA_VIVOS
		JMP FIM_DE_VIVOS

		
	FIM_DE_VIVOS:

	MOV A, #08H
	SUBB A, NUMERO_DE_VIVOS

	APAGA_COPIAS:		; APAGA OS INIMIGOS DEIXADOS PARA TRAZ DA TABELA
	INC R1
	INC R1
	MOV @R1, #0FFH
	DEC A
	JNZ APAGA_COPIAS

	

	RET


F_MAIOR_X:
	MOV A, MAIOR_X
	SUBB A, MEU_AUX
	JNC NAO_TROCA_F_MAIOR_X
	MOV A, MEU_AUX
	MOV MAIOR_X, A
	NAO_TROCA_F_MAIOR_X:
	RET

F_MENOR_X:
	MOV A, MENOR_X
	SUBB A, MEU_AUX
	JC NAO_TROCA_F_MENOR_X
	MOV A, MEU_AUX
	MOV MENOR_X, A
	NAO_TROCA_F_MENOR_X:
	RET

F_MENOR_Y:
	MOV A, MENOR_Y
	SUBB A, MEU_AUX
	JC NAO_TROCA_F_MENOR_Y
	MOV A, MEU_AUX
	MOV MENOR_Y, A
	NAO_TROCA_F_MENOR_Y:
	RET







			 
	

	

INICIALIZA_INIMIGOS:
											  ; PREENCHE OS DADOS DOS INIMIGOS
	MOV PRIMEIRA_VEZ, #01H   ; DIZ QUE JA INICIO
		
	MOV A,#ENEMIES ;COMECA COM O VALOR DA X DO INIMIGO
	MOV R0, A
	MOV DPTR,#TAB_INIMIGOS
	CLR A
	MOV R1, A
	
	LOOP_INICIA_INIMIGOS:	
	MOV A, R1
	MOVC A,@A + DPTR
	MOV @R0, A
	INC R0
	INC R1
	CJNE R1, #010H,LOOP_INICIA_INIMIGOS ; 10H EH IGUAL A 16= 2*8 INIMIGOS  
	RET





TAB_INIMIGOS:
	;COORDENADAS DO VEICULO:
	;      X,    Y ,				   
	DB 00H, 00H   
	DB 0BH, 00H
	DB	 16H, 00H
	DB	 21H, 00H
	DB 00H, 01H   
	DB 0BH, 01H
	DB	 16H, 01H
	DB	 21H, 01H


PLAYER DATA 30H
PLAYERX DATA 30H
PLAYERY DATA 31H
PLAYERLIFE DATA 32H

ENEMIES DATA 33H						   ;X = 33h y= 34H , SE NA POSICÇÃO FOR IGUAL A FFH ENTAO TA MORTO
;TABELA DE INIMIGOS						   ; Y VAI DE 0 5 COM DESLOCAMENTO DE 1
													   ; X VAI DE 0 127 COM DESLOCAMENTO NÃO ESTABELECIDO
													   ; CADA BONECO OCUPA 11 pix isso da 43
LAST_ENEMY DATA 41H 					;X = 41H T=42H

PLAYER_SHOTS DATA 43H
ENEMY_SHOTS DATA 44H
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;MINHAS ADIÇOES
PRIMEIRA_VEZ DATA 45H
INIMIGOS_DIRECAO DATA 46H
MAIOR_X	 DATA  47H
MENOR_X	DATA 48H
MENOR_Y DATA 49H
NUMERO_DE_VIVOS DATA 4AH
MEU_AUX DATA 4BH
FLAG_TROCOU_DIRECAO DATA 4CH
FLAG_GAME_OVER DATA 4DH
END
