DESLOCAMENTO_X EQU 01H
DESLOCAMENTO_Y EQU 01H
MAXIMO_X             EQU 10H
MACIMO_Y             EQU 10H
MINIMO_X             EQU  00H
MINIMO_Y             EQU 00H

ORG 0000H
	JMP INICIO
ORG 0100H
INICIO:
	MOV A, PRIMEIRA_VEZ
	JZ INICIA_VALORES
	CALL TAB_APAGAR      ; MANDAR APAGAR A TEBELA NO DISPLAY PONTO INICIAL NAVE_X
	CALL INIMIGOS
	 
;	CALL NAVE
	
	JMP INICIO

INIMIGOS:
	MOV A,INIMIGOS_DIRECAO
	JZ DIREITA
	JMP ESQUERDA
	DIREITA:
		MOV A, #INIMIGO_X
		ADD A, #15H ; ACHO QUE É O ULTIMO DA DIREITA
		MOV R0, A
		MOV A,@R0
		ADD A, DESLOCAMENTO_X           ;DESLOCAMENTO PODE MUDAR SE QUISER MAIS RAPIDO
		A GT MAXIMO_X
		JZ CONTINUA_DESLOCAMENTO
		MOV INIMIGOS_DIRECAO, #01H
		JMP CONTINUA_DESLOCAMENTO		
	ESQUERDA:
		MOV A, INIMIGO_X
		SUBB A, DESLOCAMENTO_X           ;DESLOCAMENTO PODE MUDAR SE QUISER MAIS RAPIDO
		A GT MINIMO_X
		JNZ CONTINUA_DESLOCAMENTO
		MOV INIMIGOS_DIRECAO, #00H
		JMP CONTINUA_DESLOCAMENTO
	CONTINUA_DESLOCAMENTO:
		MOV R2, NAVE_X
		MOV A, #INIMIGO_X
		MOV R0, A
		MOV R2, A

		LOOP_DESLOCAMENTO:
			
			CJE R0, , LOOP_DESLOCAMNTO
			MOV A, INIMIGOS_DIRECAO
			JZ INDO_PARA_DIREITA
			JMP INDO_PARA_ESQUERDA
			INDO_PARA_DIREITA:
				MOV A,@R0
				ADD A, #01H
				MOV @R0, A

				ADD R0, #03H
				CJNE A, NAVE_X, LOOP_DESLOCAMNTO
				CALL NOVO_TIRO
				JMP LOOP_DESLOCAMNTO
			INDO_PARA_ESQUERDA:
				MOV A, @R0
				SUB, #01H
				MOV  @R0, A
				ADD R0, #03
				CJNE A, NAVE_X, LOOP_DESLOCAMNTO
				CALL NOVO_TIRO
				JMP LOOP_DESLOCAMNTO


		


	 
	DIRECAO
	QUEM É O MAIS DA DIRECAO
	CHEGO SE MOVER CHEGA NO FIM DA TELA S OU N
	

TAB_APAGAR:
	RET

INICIA_VALORES:					  ; PREENCHE OS DADOS DOS VEICULOS
	MOV PRIMEIRA_VEZ, #01H   ; DIZ QUE JA INICIO
		
	MOV A,#NAVE_X ;COMECA COM O VALOR DA X DA NAVE
	MOV R0, A
	MOV DPTR,#CRIA_VEICULOS
	CLR A
	MOV R1, A
	
	LOOP_INICIA_VALORES:	
	MOV A, R1
	MOVC A,@A + DPTR
	MOV @R0, A
	INC R0
	INC R1
	CJNE R1, #01BH,LOOP_INICIA_VALORES ; 1BH EH IGUAL A 27= 3*8 INIMIGOS + 3 DA NAVE    
	
	MOV DPTR, #DADOS_INICIAIS ;DADOS QUE PRECISAM SER POSTOS
	CLR A
	MOVC A, @A + DPTR
	MOV INIMIGOS_DIRECAO, A	    ;DIREITA OU ESQUERDA
	MOV A, #01H
	MOVC A, @A + DPTR
	MOV VIDA, A                              ;VIDAS DA NAVE

	
	RET


CRIA_VEICULOS:
	;COORDENADAS DO VEICULO:
	;      X,    Y , STATOS				   
	DB 05H, 01H, 01H	 ; NAVE       
	DB 00H, 10H, 01H    ; INIMIGOS       
	DB	 01H, 10H, 01H
	DB	 02H, 10H, 01H
	DB	 03H, 10H, 01H
	DB	 04H, 10H, 01H
	DB	 05H, 10H, 01H
	DB	 06H, 10H, 01H
	DB	 07H, 10H, 01H

DADOS_INICIAIS:

	DB 00H  ; '0' DIREITA '1' ESQUERDA
	DB 03H	; '3' VIDAS DA NAVE


 
INIMIGOS_DIRECAO    DATA 2EH
VIDA 						DATA 2FH

PRIMEIRA_VEZ     DATA 30H ; FLAG DE INICIO DE PROGRAMA

NAVE_X                 DATA 31H
NAVE_Y                 DATA 32H
NAVE_STATOS      DATA 33H
							
INIMIGO_X			      DATA 34H
INIMIGO_y			      DATA 35H
INIMIGO_STATOS	  DATA 36H




END
